### ISSUE TITLE
CollectionView sample crashes

### ISSUE THREAD

**Issue by dbof10** [tikivn/android-template#3]
Logcat
```
 Process: vn.tiki.sample.dev, PID: 6357
                                                                  java.lang.IllegalArgumentException: unknown class java.lang.String
                                                                      at viewholders.TypeFactoryImpl.typeOf(TypeFactoryImpl.java:34)
                                                                      at vn.tiki.noadapter2.OnlyAdapter.getItemViewType(OnlyAdapter.java:103)
                                                                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5657)
                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                      at android.view.View.layout(View.java:17637)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
11-03 23:08:53.385 6357-6357/vn.tiki.sample.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by talenguyen** [comment]
It's crash because I did not implement ViewHolder for it. It's my fault.
